version: '3.4'

x-antidote-features:
  &default-features
  RING_SIZE: "4"
  ANTIDOTE_TXN_CERT: "true"
  ANTIDOTE_TXN_PROT: "clocksi"
  ANTIDOTE_RECOVER_FROM_LOG: "true"
  ANTIDOTE_META_DATA_ON_START: "true"
  ANTIDOTE_SYNC_LOG: "false"
  ANTIDOTE_ENABLE_LOGGING: "true"
  ANTIDOTE_AUTO_START_READ_SERVERS: "true"
  COOKIE: "secret"


services:
  dc2n1:
    container_name: dc2n1
    image: antidotedb/antidote:stable
    environment:
      << : *default-features
      NODE_NAME: "antidote@dc2n1"
    ports:
      - "8101:8087"
      - "8111:3001"

  dc2n2:
    container_name: dc2n2
    image: antidotedb/antidote:stable
    environment:
      << : *default-features
      NODE_NAME: "antidote@dc2n2"
    ports:
      - "8102:8087"
      - "8112:3001"

  link-cluster-1:
    image: peterzel/antidote-connect
    command: ['--createDc', 'dc2n1:8087', 'antidote@dc2n2']
    depends_on:
      - dc2n1
      - dc2n2